apiVersion: v1
kind: Service
metadata:
  name: grade-submission-api
  annotations:
    cloud.google.com/backend-config: '{"default": "grade-backend-config"}'
spec:
  type: ClusterIP
  selector:
    app: grade-submission
  ports:
  - name: http
    port: 3000
    targetPort: 3000
